# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BINARY_7Z "")
set(CPACK_BINARY_BUNDLE "")
set(CPACK_BINARY_CYGWIN "")
set(CPACK_BINARY_DEB "")
set(CPACK_BINARY_DRAGNDROP "")
set(CPACK_BINARY_FREEBSD "")
set(CPACK_BINARY_IFW "")
set(CPACK_BINARY_NSIS "")
set(CPACK_BINARY_NUGET "")
set(CPACK_BINARY_OSXX11 "")
set(CPACK_BINARY_PACKAGEMAKER "")
set(CPACK_BINARY_PRODUCTBUILD "")
set(CPACK_BINARY_RPM "")
set(CPACK_BINARY_STGZ "")
set(CPACK_BINARY_TBZ2 "")
set(CPACK_BINARY_TGZ "")
set(CPACK_BINARY_TXZ "")
set(CPACK_BINARY_TZ "")
set(CPACK_BINARY_WIX "")
set(CPACK_BINARY_ZIP "")
set(CPACK_BUILD_SOURCE_DIRS "/home/sirius/Documents/Libmodules/zwave/zip_gateway/v7.17.1/Source/zipgateway-7.17.01-Source/usr/local;/home/sirius/Documents/Libmodules/zwave/zip_gateway/v7.17.1/Source/zipgateway-7.17.01-Source/usr/local")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "i386")
set(CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA "/home/sirius/Documents/Libmodules/zwave/zip_gateway/v7.17.1/Source/zipgateway-7.17.01-Source/usr/local/files/scripts/20_04/postinst;/home/sirius/Documents/Libmodules/zwave/zip_gateway/v7.17.1/Source/zipgateway-7.17.01-Source/usr/local/files/scripts/config;/home/sirius/Documents/Libmodules/zwave/zip_gateway/v7.17.1/Source/zipgateway-7.17.01-Source/usr/local/files/scripts/postrm;/home/sirius/Documents/Libmodules/zwave/zip_gateway/v7.17.1/Source/zipgateway-7.17.01-Source/usr/local/files/scripts/templates;/home/sirius/Documents/Libmodules/zwave/zip_gateway/v7.17.1/Source/zipgateway-7.17.01-Source/usr/local/conffiles")
set(CPACK_DEBIAN_PACKAGE_DEPENDS "libusb-1.0-0, libssl1.1, radvd:amd64 | i386, parprouted:amd64 | i386, bridge-utils:amd64 | i386, libjson-c2 | libjson-c3 | libjson-c4, net-tools, zip, unzip")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Silicon Labs")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake-3.16/Templates/CPack.GenericDescription.txt")
set(CPACK_FILE_NAME_EXTRA "ubuntu_20_04")
set(CPACK_GENERATOR "TBZ2")
set(CPACK_IGNORE_FILES "/build.*/;Jenkinsfile;docker/;/\\..*;/src/scxml/;/pkgconfig.h.cmake.in;/sonar-project.properties")
set(CPACK_INSTALLED_DIRECTORIES "/home/sirius/Documents/Libmodules/zwave/zip_gateway/v7.17.1/Source/zipgateway-7.17.01-Source/usr/local;/")
set(CPACK_INSTALL_CMAKE_PROJECTS "")
set(CPACK_INSTALL_PREFIX "/usr/local")
set(CPACK_MODULE_PATH "/home/sirius/Documents/Libmodules/zwave/zip_gateway/v7.17.1/Source/zipgateway-7.17.01-Source/usr/local/cmake/;/home/sirius/Documents/Libmodules/zwave/zip_gateway/v7.17.1/Source/zipgateway-7.17.01-Source/usr/local")
set(CPACK_NSIS_DISPLAY_NAME "zipgateway 7.17.01")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "zipgateway 7.17.01")
set(CPACK_OUTPUT_CONFIG_FILE "/home/sirius/Documents/Libmodules/zwave/zip_gateway/v7.17.1/Source/zipgateway-7.17.01-Source/usr/local/CPackConfig.cmake")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake-3.16/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "zipgateway built using CMake")
set(CPACK_PACKAGE_FILE_NAME "zipgateway-7.17.01-Source")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "zipgateway 7.17.01")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "zipgateway 7.17.01")
set(CPACK_PACKAGE_NAME "zipgateway")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Humanity")
set(CPACK_PACKAGE_VERSION "7.17.01")
set(CPACK_PACKAGE_VERSION_MAJOR "7")
set(CPACK_PACKAGE_VERSION_MINOR "17")
set(CPACK_PACKAGE_VERSION_PATCH "01")
set(CPACK_PACKAGING_INSTALL_PREFIX "/usr/local")
set(CPACK_RESOURCE_FILE_LICENSE "/usr/share/cmake-3.16/Templates/CPack.GenericLicense.txt")
set(CPACK_RESOURCE_FILE_README "/usr/share/cmake-3.16/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/usr/share/cmake-3.16/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_PACKAGE_SOURCES "ON")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_7Z "")
set(CPACK_SOURCE_CYGWIN "")
set(CPACK_SOURCE_GENERATOR "TBZ2")
set(CPACK_SOURCE_IGNORE_FILES "/build.*/;Jenkinsfile;docker/;/\\..*;/src/scxml/;/pkgconfig.h.cmake.in;/sonar-project.properties")
set(CPACK_SOURCE_INSTALLED_DIRECTORIES "/home/sirius/Documents/Libmodules/zwave/zip_gateway/v7.17.1/Source/zipgateway-7.17.01-Source/usr/local;/")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/sirius/Documents/Libmodules/zwave/zip_gateway/v7.17.1/Source/zipgateway-7.17.01-Source/usr/local/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "zipgateway-7.17.01-Source")
set(CPACK_SOURCE_RPM "")
set(CPACK_SOURCE_TBZ2 "")
set(CPACK_SOURCE_TGZ "")
set(CPACK_SOURCE_TOPLEVEL_TAG "Linux-Source")
set(CPACK_SOURCE_TXZ "")
set(CPACK_SOURCE_TZ "")
set(CPACK_SOURCE_ZIP "")
set(CPACK_STRIP_FILES "")
set(CPACK_SYSTEM_NAME "Linux")
set(CPACK_TOPLEVEL_TAG "Linux-Source")
set(CPACK_WIX_SIZEOF_VOID_P "4")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/home/sirius/Documents/Libmodules/zwave/zip_gateway/v7.17.1/Source/zipgateway-7.17.01-Source/usr/local/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
